### ISSUE TITLE
Saving module settings

### ISSUE THREAD

**Issue by El-Jefe** [yapatel/human-prc#10]
The BB kids are telling me that they are unable to save the settings for the human-prc module. I have not attempted to do so, but will try to replicate the issue

**Comment by yapatel** [comment]
Please describe what “save settings” means…

> On Feb 24, 2015, at 18:26, El-Jefe <notifications@github.com> wrote:
> 
> The BB kids are telling me that they are unable to save the settings for the human-prc module. I have not attempted to do so, but will try to replicate the issue
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/yapatel/human-prc/issues/10>.
> 

Yogi A. Patel
@yapatel525 <https://twitter.com/yapatel525>

**Comment by El-Jefe** [comment]
Sorry. I am trying to write these as I get them. They mean that they are trying to save a set of episodes (i.e. paced1,unpaced with perturbation at 10s, paced2, etc) 

----- Original Message -----
