### ISSUE TITLE
Problems playing module

### ISSUE THREAD

**Issue by El-Jefe** [yapatel/human-prc#17]
On Achilles, the module (with the sequence of episodes I gave you), will play two tones simultaneously upon starting followed by 3 tones at (what seem to be) the correct times, then stops playing all together.

**Comment by yapatel** [comment]
Can you please clarify the steps you took prior to this occurring? Is this after running a full trial and then the module pausing? Or pausing the module in the middle of an episode and then restarting? 


The steps leading up to this bug would be helpful in reproducing the error and tracking down where it failed.

**Comment by El-Jefe** [comment]
I haven't been able to run a full trial, because this happens immediately upon starting. 

----- Original Message -----
