### ISSUE TITLE
perturbation

### ISSUE THREAD

**Issue by El-Jefe** [yapatel/human-prc#7]
In order to generate a real phase response curve, we need to have the perturbations triggered by a delay from the subject's tap instead of a time from the beginning of the episode (i.e. 100ms from the subject's 8th tap of the episode).

**Comment by yapatel** [comment]
To provide phase-specific perturbations, enter the time of the perturbation into the module with the time in the trial. For example, if you want a perturbation 100ms after the 10th tone, then at a rate of 120pm and 20s trial duration, you should enter 5.1 into the module.
